### ISSUE TITLE
redmine not accessable after plugin installation

### ISSUE THREAD

**Issue by teatower** [5inf/redmine_wikiapproval#1]
Hello there,

thank you for your time and efforts in programming this plugin.
After placing it in the plugins directory and restarting, my redmine is no longer accessable at all.

log reads as follows:
ActionView::Template::Error (undefined method `plugin_redmine_wikiaproval' for #<Class:0x00005587c8e4ba60>
Did you mean?  plugin_redmine_crm):
    123:
    124: <div id="ajax-indicator" style="display:none;"><span><%= l(:label_loading) %></span></div>
    125: <div id="ajax-modal" style="display:none;"></div>
    126:
    127: </div>
    128: </div>
    129: <%= call_hook :view_layouts_base_body_bottom %>

plugins/redmine_wikiapproval/lib/wikiapproval_macro_hook.rb:7:in `view_layouts_base_body_bottom'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:98:in `call_hook'
app/views/layouts/base.html.erb:126:in `_app_views_layouts_base_html_erb___4143425724248232463_70118782380600'
app/views/layouts/admin.html.erb:8:in `_app_views_layouts_admin_html_erb__192241302694417942_70118782132060'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:72:in `call'

Redmine version 4.1.0.stable
Ruby version 2.5.5-p157 (2019-03-15)
Rails version 5.2.4.1

Do you can make anything out of that?
Thank you very much in advance!

Kind regards,

Tom

**Comment by 5inf** [comment]
Hi Tom,

try deleting the folders app and lib. They are not neccesarry for the plugin at the moment. The are leftovers the not yet finished plugin configuration and might cause the problem.

Regards
Holger

**Comment by teatower** [comment]
Hi Holger,

thank you for getting back to me. After deleting the named folders, I have my redmine back - thank you. Hardcoding tags: für mich kein Problem ;-)
But I am a bit helpless in how to exactly call a macro within a wiki-page.
I looked up the redmine-macros page and it says {{macroname(arg1, arg2)}}
So looked into the init.rb file and tried 
`{{wikiapproval(Status der Arbeitsanweisung:)}}`
but that displays exactly this string on the wikipage.

Could you spend another minute to provide a hint for me?
Thank you!
Schönes Wochenende!

Tom

**Comment by 5inf** [comment]
Just write the text {{wikiapproval}} somewhere, ideally very close to the top, on the page.
The parameter in brackets is not really necessary or used.
You can approve a page by editing the page and starting your comment to the edit with the string "Freigegeben: "

In general, you can use the build in redmine macro {{macro_list}} to get a list of all macros available in your redmine installation and descriptions on how to use them.
